### ISSUE TITLE
add Here API

### ISSUE THREAD

**Issue by yemM** [1001Pharmacies/geolocation-bundle#13]
https://developer.here.com/geocoder

**Comment by crazyball** [comment]
"Here.com API" returning results with a "relevance" (between 0 and 1, 1 is the best). Some others providers are doing the same. Another parameter for Here.com Api is "MatchLevel" : 

```
MatchLevel : 
LocationType (element of Location) is specific to the result and not just point for any result. LocationType is
address: for MatchLevel houseNumber, street, intersection
area: for MatchLevel country, state, county, city, district, postalCode
```

What we should be able to do is to define a parameter (app parameter / bundle parameter or both) with a minimum acceptable relevance in order to accept the provider's result or fallback to next provider if this value is to low. For this provider we can also check the "MatchLevel" with "street" or "houseNumber" as a good result and others as a bad result.

**Comment by methylbro** [comment]
ok.

For the moment we could consider that the pull request `#18 added Here.com Provider` do the job.
But we have to think about some customed provider configurator and also manage the result relevance when it's possible.

thx @crazyball :)

**Comment by crazyball** [comment]
We also should be able to add multiple parameters to our Locator's constructor because here, the provider doesn't have a unique Api Key but 2 parameters (Application Code and Application Id) to authenticate the API and also have two endpoints. Actually we just kind of hack the current Locator by concatenating the api keys and endpoints (see here.com doc)
